import type { LandscapeCategory, ParadigmRow } from './types'

// 方案对比：站在 PM 视角评估现有生产级 RAG 路线。
// 结论先行：什么时候该买、什么时候该自研、什么时候用本工作台当设计沙盘。
// 诚实前提：OpenRAG Forge 是设计沙盘与教学载体，不是这些方案的竞品。

export const LANDSCAPE_INTRO: string[] = [
  '选 RAG 方案本质上是三个问题：数据能不能出域（合规轴）、团队要多深的定制权（控制轴）、愿意养多少运维（成本轴）。下面每个方案我都按同一组维度拆：定位、装配方式、可观测性、定制深度、成本运维、合规、对 PM 的意义、优劣、何时该选、与本工作台的差异。',
  '先说清 OpenRAG Forge 站在哪：它是「可拆、可证明」的设计沙盘——用来在采购或自研决策之前，把候选链路装配出来、跑通、用 Trace 验证每一环的真实行为。它故意不站在「托管规模」「算法完备」这两个位置：没有弹性伸缩，稀疏/重排还是占位。用它做决策依据，然后把生产流量交给下面某个方案或自研栈。',
]

export const PARADIGMS_INTRO =
  '在看具体产品之前，先分清三代范式——面试里被问「Advanced RAG 和 Naive RAG 差在哪」时，这张表就是答案骨架。'

export const PARADIGMS: ParadigmRow[] = [
  {
    name: 'Naive RAG',
    definition: '最短链路：切分 → 向量召回 Top-K → 直接拼进 Prompt 生成。',
    pipeline: 'chunk → embed → dense top-k → prompt → LLM',
    strengths: '实现快、行为可预测、故障面小；是一切评测的基线。',
    weaknesses: '召回天花板低：措辞不匹配就漏、精确 token 匹配弱、噪声直接进 Prompt；没有查询理解，长问题/多跳问题崩。',
    forgeStance: '本仓库的 v0_1_dense 就是标准 Naive RAG，且是唯一全 live 的链路——我们诚实地站在这里。',
  },
  {
    name: 'Advanced RAG',
    definition: '在检索前后加优化模块：查询改写/扩展（pre-retrieval），混合召回、重排、上下文压缩（post-retrieval）。',
    pipeline: 'query rewrite → hybrid(dense+sparse) → RRF → rerank → context compress → LLM',
    strengths: '生产界的事实标准形态；重排通常是单点收益最大的模块；混合检索兜住专有名词。',
    weaknesses: '每加一个模块都加时延与运维面；模块间相互影响，没有评测基线时无法归因收益。',
    forgeStance: '目录里的 v0_2~v0_5 Recipe 描绘了这个形态，但稀疏/RRF/重排是占位——画布能装配出 Advanced RAG 的「形」，执行是 Naive 的「实」。这正是拿来讲「目录能力 ≠ 已实现能力」的教具。',
  },
  {
    name: 'Modular RAG',
    definition: '把 RAG 拆成可编排的算子图：路由、多路检索、评分、有界纠错循环、Agent 工具调用皆为模块，按需组合。',
    pipeline: '任意 DAG：intent route → 多分支检索 → grade → (bounded) corrective loop → generate → gate',
    strengths: '表达力最强，能针对场景差异化装配；失败可以局部替换模块而不是重写全链。',
    weaknesses: '复杂度爆炸的风险：无界循环、不可复现的动态路径；对可观测性的要求最高。',
    forgeStance: '本仓库的 Recipe 编译器（typed DAG + 显式 bounded_corrective + 内容哈希）就是 Modular RAG 的骨架设计——骨架是 live 的，血肉（各模块算法）多数未填。',
  },
]

export const LANDSCAPE: LandscapeCategory[] = [
  {
    id: 'managed',
    title: '托管套件（买）',
    intro: '数据出域可接受、想最快上线、不想养检索团队时的选项。共同风险：黑盒环节多、深度定制会顶到天花板、成本随规模非线性。',
    entries: [
      {
        id: 'azure-ai-search',
        name: 'Azure AI Search',
        category: 'managed',
        positioning: '微软系企业检索服务：向量 + BM25 + 语义重排一体，配合 Azure OpenAI 组成官方推荐 RAG 栈。',
        assembly: '门户/SDK 配置索引器（indexer）自动抓取数据源，字段映射 + 技能集（skillset）做抽取；检索端一个 API 同时要向量、关键词、语义重排结果。',
        observability: '有查询指标与诊断日志，但重排与语义排序是黑盒——只给分数不给依据；无逐环节 Trace。',
        customization: '中等：analyzer、评分 profile、向量维度可配；但切分策略受限、重排模型不可换。',
        costOps: '按副本/分区计费 + 语义排序按查询计费；几乎零运维，但规模大后账单显著。',
        compliance: '数据入 Azure 边界；有区域、私有网络、行业合规认证，金融/政企常因「已在 Azure」而顺势选它。',
        pmTakeaway: '当组织已经站在 Azure 上，它是阻力最小的路径——PM 该关注的不是技术而是账单模型与黑盒环节的验收方式。',
        strengths: ['混合检索 + 语义重排开箱即用', '与 Azure 生态（AAD、Purview）无缝', '企业合规认证齐全'],
        weaknesses: ['重排黑盒，坏 case 无法归因', '切分/嵌入策略定制受限', '成本模型复杂，语义排序另计费'],
        whenToPick: '已在 Azure、要 3 个月内上线、接受托管黑盒、检索不是核心差异化能力时。',
        vsForge: 'Forge 的每一环都有 Trace 可归因，Azure 的语义重排给不出「为什么这条排第一」；反过来 Azure 的混合检索是真实现，Forge 的还是占位。用 Forge 设计验收标准，再去验收 Azure。',
      },
      {
        id: 'aws-kendra',
        name: 'AWS Kendra（+ Bedrock Knowledge Bases）',
        category: 'managed',
        positioning: 'AWS 的企业智能搜索：Kendra 主打开箱即用的自然语言企业搜索与 50+ 连接器；新项目更多走 Bedrock Knowledge Bases（托管 RAG 流水线）。',
        assembly: '配置数据源连接器（S3/SharePoint/Confluence…）→ 自动抓取与索引；Bedrock KB 则是选数据源、选向量库（OpenSearch Serverless 等）、选模型，托管切分与嵌入。',
        observability: 'CloudWatch 指标 + 查询分析；检索内部（怎么切、怎么排）基本不可见。',
        customization: '低：Kendra 的切分、排序不可定制是常见抱怨；Bedrock KB 可选分块参数但仍是模板级。',
        costOps: 'Kendra 按版本包月起步价高（开发者版也不便宜），是「为省人力付钱」的定价；运维接近零。',
        compliance: 'AWS 边界内，IAM 细粒度权限过滤（ACL-aware 检索）是它的强项——搜索结果按用户权限裁剪。',
        pmTakeaway: '它把「权限感知检索」这个企业刚需做成了默认能力——这是自研最容易低估的坑。评估任何方案时都该把 ACL 过滤列入验收单。',
        strengths: ['连接器生态丰富，接企业内容源最快', '权限感知检索开箱即用', '与 Bedrock 模型栈原生集成'],
        weaknesses: ['定制深度全场最低之一', '起步价高，小场景不划算', '检索行为黑盒，调优手段少'],
        whenToPick: '内容散在 SharePoint/Confluence 等系统、权限过滤是硬需求、预算充足且不想碰检索内部时。',
        vsForge: 'Forge 完全没有连接器与 ACL 体系（设计债之一：连 KB 隔离都没有）；但 Forge 能让你看见切分与召回的每一步，Kendra 不能。两者互补关系明显：用 Forge 理解环节，用 Kendra 省人力。',
      },
      {
        id: 'vertex-rag',
        name: 'Google Vertex AI（RAG Engine / Search）',
        category: 'managed',
        positioning: 'Google 云的两层供给：Vertex AI Search 是端到端托管检索；RAG Engine 是可选组件的托管编排（可换向量库、可配切分）。',
        assembly: 'RAG Engine 里声明 corpus → 导入数据（可配 chunk 参数）→ 选向量后端（RagManagedDb/Pinecone/pgvector 等）→ 检索 API 接 Gemini。',
        observability: '云监控指标为主；比纯黑盒略好（组件可选所以边界清楚），但没有业务级证据链。',
        customization: '中等偏上（托管阵营里）：向量库、嵌入模型、切分参数可换，接近「托管的 LlamaIndex」。',
        costOps: '按组件计费（存储、嵌入、检索、生成分开）；运维低，但多组件账单需要专人看。',
        compliance: 'Google 云边界；region 与 CMEK 支持齐全；国内可用性是实际决策里最大的问题。',
        pmTakeaway: '「托管但组件可换」是一条中间路线——PM 可以把它当作「不想养运维、但要保留换件权」的选项。',
        strengths: ['托管阵营里定制自由度较高', '与 Gemini 长上下文能力协同', '组件计费边界清楚'],
        weaknesses: ['生态锁定 Google 云', '社区案例少于 Azure 路线', '国内合规/可用性受限'],
        whenToPick: '已用 GCP、想要托管运维但保留换向量库/嵌入模型的权力时。',
        vsForge: '设计理念最接近 Forge（组件可换、边界显式），差别是它真的托管、真的实现了各组件；Forge 则把「组件边界」做到了画布和 Trace 上供人审查。',
      },
      {
        id: 'openai-assistants',
        name: 'OpenAI Assistants / File Search（Responses API）',
        category: 'managed',
        positioning: '模型厂自带的最短路径 RAG：上传文件到 vector store，模型侧自动切分、嵌入、检索、注入。',
        assembly: '几行代码：创建 vector store → 传文件 → 挂到 assistant/response 上。切分与检索策略几乎全默认（可调 chunk 大小与 max_num_results 等少量参数）。',
        observability: '几乎为零：能拿到引用的文件片段，但召回了什么、怎么排的、为什么没召回，均不可见。',
        customization: '最低：嵌入模型不可换、检索算法不可见、无法插入重排或过滤。',
        costOps: '按存储 GB/天 + 调用计费；零运维。规模大后存储费用可观。',
        compliance: '数据交给模型厂托管；企业版有数据不训练承诺，但对强合规行业往往仍过不了数据出域审查。',
        pmTakeaway: '它是验证「RAG 对这个业务有没有用」的最快原型工具——一天出 demo。但把它当生产架构，等于把召回质量的解释权完全交出去。',
        strengths: ['上手最快，原型成本最低', '与模型能力（工具调用）原生协同', '零运维'],
        weaknesses: ['黑盒程度全场最高', '坏 case 无法归因也无法修', '数据出域，强合规场景直接出局'],
        whenToPick: '做可行性验证、内部工具、文档量小且不敏感的场景。',
        vsForge: '两个极端：Assistants 把所有环节藏起来换取速度，Forge 把所有环节摊开换取可证明。我的推荐组合：用 Assistants 一天验证价值，用 Forge 设计生产形态，再决定买谁/建什么。',
      },
    ],
  },
  {
    id: 'orchestration',
    title: '开源编排框架（建）',
    intro: '自研阵营的地基选择。共同点：不解决托管，运维自己扛；差异在抽象层级（代码库 vs 低代码平台）与生态深度。',
    entries: [
      {
        id: 'llamaindex',
        name: 'LlamaIndex',
        category: 'orchestration',
        positioning: '以「数据接入 + 索引抽象」为核心的 RAG 优先框架：Document/Node 模型、多种索引结构、查询引擎。',
        assembly: '写 Python/TS 代码：Reader 读数据 → NodeParser 切分 → 建索引（向量/摘要/树/图）→ QueryEngine 组合检索与合成；高级模块（重排、子问题分解）即插即用。',
        observability: '回调体系 + 与 Langfuse/Arize 等观测平台集成；比自己裸写好，但证据链要自己设计。',
        customization: '高：每个环节都有接口可换实现；RAG 相关的算法组件（各类 retriever/reranker）生态最全之一。',
        costOps: '框架免费，成本在工程团队；版本迭代快，升级维护是持续开销。',
        compliance: '自托管，数据不出域——这是开源阵营对托管阵营的根本优势。',
        pmTakeaway: '如果团队决定自研且以「文档问答」为核心，LlamaIndex 的抽象最贴合问题域；PM 要盯的是版本快速演进带来的 API 变动成本。',
        strengths: ['RAG 专用抽象最完整', '算法组件生态丰富', '文档与案例多'],
        weaknesses: ['抽象层级多，调试时要翻框架源码', 'API 变动频繁', '生产化（部署/多租户）要自己补'],
        whenToPick: '自研、以文档问答为主、团队有 Python 工程能力时的默认起点。',
        vsForge: 'Forge 的 Recipe/Block/Chunk 概念与 LlamaIndex 的 Pipeline/Document/Node 同构，但 Forge 把结构做成了可编译、可哈希、可在画布装配的数据，并强制诚实标注；LlamaIndex 的组合在代码里，可观测性靠外挂。',
      },
      {
        id: 'langchain',
        name: 'LangChain / LangGraph',
        category: 'orchestration',
        positioning: '通用 LLM 应用编排：LangChain 提供组件生态，LangGraph 提供带状态、带循环控制的图编排——RAG 只是其应用之一。',
        assembly: '代码组合 Runnable/链；LangGraph 用显式状态机图装配（节点 + 条件边 + checkpointer），corrective RAG 这类循环流程是它的主场。',
        observability: 'LangSmith 是全生态最成熟的 LLM 观测产品之一：逐步 trace、数据集回归、人工标注闭环。',
        customization: '极高，但代价是抽象漂移：版本间概念变化大（Chain→LCEL→LangGraph），团队要持续跟进。',
        costOps: '框架免费，LangSmith 商业计费；工程与升级成本同 LlamaIndex 量级。',
        compliance: '自托管；LangSmith 云版涉及 trace 数据出域，需要选择自托管版。',
        pmTakeaway: '当产品会从 RAG 演进到 Agent（多步工具调用）时，LangGraph 的图 + 状态 + 有界循环模型是最顺的路径——这也验证了「用显式图管理循环」是行业共识。',
        strengths: ['生态最大、集成最多', 'LangGraph 的循环/状态控制成熟', 'LangSmith 观测闭环完整'],
        weaknesses: ['抽象历史包袱重，学习曲线陡', '简单场景容易过度工程', '版本升级成本高'],
        whenToPick: '产品路线明确会走向 Agent 化、且愿意投入跟进生态演进的团队。',
        vsForge: 'Forge 的 bounded_corrective（编译期强制显式循环上限）与 LangGraph 的图循环控制是同一个设计判断的两种实现；Forge 把它做到了编译器里并配了画布可视化，LangGraph 做在运行时框架里且生态成熟得多。',
      },
      {
        id: 'haystack',
        name: 'Haystack（deepset）',
        category: 'orchestration',
        positioning: '工程化取向的开源 LLM/检索框架：显式 Pipeline DAG、组件强类型接口、面向生产部署（deepset 提供商业平台）。',
        assembly: '声明组件（retriever/ranker/generator）→ 用 add_component/connect 显式连成 DAG，支持 YAML 序列化 pipeline——与 Forge 的 Recipe JSON 思路几乎同构。',
        observability: '组件级 tracing 集成（OTel、Langfuse），pipeline 可序列化带来一定可复现性。',
        customization: '高，且接口边界比 LangChain 稳定；检索侧（Elasticsearch/OpenSearch/Qdrant 集成）传统深厚。',
        costOps: '开源自托管；deepset Cloud 提供托管选项。工程成本中等。',
        compliance: '自托管为主，欧洲背景（deepset）对 GDPR 场景友好。',
        pmTakeaway: 'Haystack 证明了「显式类型化 DAG」是可以在生产里落地的工程路线——Forge 的编译器设计有它的影子；选它意味着选「稳定边界」而不是「最大生态」。',
        strengths: ['Pipeline 显式、可序列化、类型清楚', 'API 稳定性口碑好', '检索工程传统深'],
        weaknesses: ['生态与社区规模小于 LangChain/LlamaIndex', '国内案例较少', '高级 RAG 算法组件相对少'],
        whenToPick: '重视工程秩序与长期维护性、检索场景为主的团队。',
        vsForge: '理念最近的亲戚：都是 typed DAG + 可序列化 pipeline。差异是 Haystack 组件全部真实现且生产可用，Forge 用编译哈希 + Evidence Capsule + 诚实徽标把「可证明」推得更极端，但算法组件多数未实现。',
      },
      {
        id: 'dify',
        name: 'Dify',
        category: 'orchestration',
        positioning: '开源 LLMOps 低代码平台：可视化编排 + 知识库 + 应用发布 + 团队协作，一体化交付。',
        assembly: '网页画布拖节点（知识检索、LLM、条件分支、工具），知识库在后台配置（切分、嵌入、混合检索、重排均有 UI 开关）。',
        observability: '应用级日志与标注、用量统计；有运行记录但环节级证据链弱于代码框架 + LangSmith 的组合。',
        customization: '中等：UI 暴露的开关内很自由（含混合检索/重排选项），超出开关范围要改平台源码。',
        costOps: '自托管（Docker Compose 起步）或用其云版；对非工程团队的总拥有成本全场最低之一。',
        compliance: '可完全自托管，数据不出域；国内采用率高。',
        pmTakeaway: 'Dify 是「让业务团队自己装配 AI 应用」的产品化标杆——它验证了本工作台押注的方向（可视化装配 + 知识库开关）有真实市场。',
        strengths: ['非工程角色可独立上手', '知识库高级功能（混合/重排）有 UI 开关且真实现', '自托管方便，社区活跃'],
        weaknesses: ['深度定制顶到平台边界', '检索内部行为可见性有限', '大规模多租户要自己加固'],
        whenToPick: '团队工程资源少、要快速交付多个内部 AI 应用、接受平台边界时。',
        vsForge: '同为可视化装配，分工不同：Dify 优化「快速交付应用」，开关背后是真实现但不可深查；Forge 优化「看清每一环节」，画布连到编译器与 Trace，但功能广度远小于 Dify。面试里这是一组很好的对照案例。',
      },
      {
        id: 'fastgpt',
        name: 'FastGPT',
        category: 'orchestration',
        positioning: '国内活跃的开源知识库问答平台：Flow 可视化编排 + 知识库管理 + 对外 API，主打私有化部署问答场景。',
        assembly: '可视化 Flow 编排（问题分类、知识库搜索、HTTP 节点等）；知识库支持多种切分模式、混合检索与重排序开关。',
        observability: '对话日志与引用来源展示；环节级追踪有限。',
        customization: '中等：Flow 内自由，平台外需改源码（Node.js 栈）。',
        costOps: '自托管（依赖 MongoDB/PG+向量扩展）；商业版另有授权。中文文档齐全，国内部署阻力小。',
        compliance: '可全私有化，适配国内合规环境（对接国产模型方便）。',
        pmTakeaway: '在国内私有化问答这个细分市场，FastGPT 的「知识库 + Flow + API」组合就是需求清单本身——做竞品分析时值得逐功能拆。',
        strengths: ['中文生态与国产模型适配好', '私有化部署路径成熟', '知识库功能完整（含重排开关）'],
        weaknesses: ['国际社区与英文资料少', '架构深度定制成本高', '观测能力偏应用层'],
        whenToPick: '国内私有化、中文为主、需要快速搭知识库问答并对外提供 API 时。',
        vsForge: '面向交付 vs 面向解释：FastGPT 把功能做全给你用，Forge 把机制拆开给你看。若目标是上线，选 FastGPT 这类；若目标是设计能力与验收标准，用 Forge 推演后再选型。',
      },
      {
        id: 'ragflow',
        name: 'RAGFlow',
        category: 'orchestration',
        positioning: '以「深度文档理解」为差异点的开源 RAG 引擎：版面分析驱动的智能切分、切分结果人工可干预、引用可视化。',
        assembly: '上传文档 → 选文档模板（论文/合同/简历…按版面类型）→ 引擎做版面感知切分（DeepDoc）→ 知识库问答或 Agent 编排；切分块可人工审阅修正。',
        observability: '切分结果可视化（块与原文版面对照）是它的招牌——数据面可见性全场最高；查询面观测一般。',
        customization: '文档解析层定制强；编排层向 Agent 工作流演进中。',
        costOps: '自托管，组件较重（依赖 Elasticsearch/Infinity 等）；解析质量换来的资源开销不小。',
        compliance: '自托管，数据不出域。',
        pmTakeaway: 'RAGFlow 把「垃圾进垃圾出」问题正面攻坚——它证明数据面（解析与切分质量）是 RAG 质量的第一杠杆，这与本仓库把解析路由做成 live 节点的判断一致。',
        strengths: ['版面感知解析显著优于朴素切分', '切分结果可人工校对', '引用定位到原文版面'],
        weaknesses: ['部署重、资源消耗高', '查询侧编排能力较新', '深度绑定其解析引擎'],
        whenToPick: '文档以复杂版式（合同、报告、扫描件）为主、解析质量是主要瓶颈时。',
        vsForge: 'Forge 的解析路由（签名检测 + reason_codes + Ingest Trace）与 RAGFlow 的 DeepDoc 方向一致但深度差一个量级——Forge 的 PDF 解析只按页取文本层、不做版面分析（诚实标注在节点说明里）。文档复杂度高的场景应直接考虑 RAGFlow 类引擎。',
      },
    ],
  },
  {
    id: 'search-platform',
    title: '企业检索中台（已有搜索基建时）',
    intro: '当组织已经有搜索团队与倒排索引基建时，RAG 的检索层往往不该新建向量库，而是升级现有中台。',
    entries: [
      {
        id: 'elastic-hybrid',
        name: 'Elasticsearch / OpenSearch hybrid',
        category: 'search-platform',
        positioning: '通用搜索引擎加向量能力：BM25 + dense kNN + RRF 融合在同一引擎内完成，一套集群同时服务传统搜索与 RAG。',
        assembly: '索引 mapping 里同时定义 text 字段与 dense_vector 字段；查询用 hybrid/RRF 语法一次拿融合结果；ELSER（Elastic 学习型稀疏向量）可作第三路。',
        observability: '搜索基建级：慢查询日志、profile API、集群监控成熟；但这是「搜索观测」不是「RAG 证据链」。',
        customization: '检索层定制极深（analyzer、评分脚本、融合权重）；RAG 其余环节（切分、生成、评测）不归它管。',
        costOps: '集群运维是真实成本（分片、内存、升级）；已有 ES 团队则边际成本低。',
        compliance: '自托管或云托管皆可，权限模型（文档级安全）成熟。',
        pmTakeaway: '「要不要专用向量库」的答案常常是「不要」：已有 ES/OpenSearch 时，hybrid 一个引擎同时给 BM25 与向量，省掉双索引一致性这个长期税。',
        strengths: ['一个引擎两路召回，天然混合检索', '倒排能力（过滤、聚合、权限）无可替代', '运维生态与人才市场成熟'],
        weaknesses: ['纯向量性能/成本不如专用向量库', '大规模高维向量的内存开销大', 'RAG 上层环节仍需别的框架'],
        whenToPick: '已有 ES/OpenSearch 基建与团队、需要混合检索与复杂过滤、向量规模千万级以内时。',
        vsForge: 'Forge 的稀疏检索与 RRF 恰恰是占位——ES hybrid 是这两个占位节点的「真身」。向量库专章里专门讨论了「向量库 vs 倒排引擎」的分工与选择。',
      },
      {
        id: 'vespa',
        name: 'Vespa',
        category: 'search-platform',
        positioning: '大规模在线检索与排序平台（前雅虎搜索内核开源）：向量、倒排、结构化过滤、多阶段机器学习排序在引擎内一体执行。',
        assembly: '声明式 schema + 排序表达式（rank-profile），第一阶段粗排、第二阶段模型精排都在数据节点本地算——「把计算搬到数据处」。',
        observability: '引擎级 metrics 完整；排序表达式显式可审查（比黑盒重排透明）。',
        customization: '全场最深：排序阶段、张量计算、召回策略全部可编程——代价是学习曲线全场最陡。',
        costOps: '自托管运维复杂度高，或用 Vespa Cloud；适合有专职检索工程师的团队。',
        compliance: '自托管可控。',
        pmTakeaway: 'Vespa 代表「检索即产品核心」的终局形态：当排序质量直接等于收入（电商、推荐、大规模问答）时，多阶段排序一体化引擎是正确投资；一般知识库问答用它是过度设计。',
        strengths: ['多阶段排序引擎内一体完成（省一跳网络）', '超大规模在线性能标杆', '排序逻辑显式可编程'],
        weaknesses: ['学习与运维成本全场最高', '社区规模小、招人难', '小场景严重过度设计'],
        whenToPick: '检索排序是产品核心竞争力、规模到亿级文档、团队有检索工程深度时。',
        vsForge: '两端对照：Forge 用画布把「多阶段检索」讲清楚（dense→fusion→rerank 的 DAG），Vespa 把同样的阶段在引擎内做到极致性能。Forge 是黑板，Vespa 是发动机。',
      },
    ],
  },
  {
    id: 'graph',
    title: '图增强路线（GraphRAG 类）',
    intro: '当问题是「关系与全局」而不是「片段与局部」时，向量检索的独立片段假设失效——图路线用实体关系与社区摘要补这个缺口。',
    entries: [
      {
        id: 'graphrag',
        name: 'GraphRAG 类（Microsoft GraphRAG / Neo4j 方案）',
        category: 'graph',
        positioning: '用 LLM 从语料抽取实体-关系图，构建层级社区摘要；查询时结合图遍历（局部）与社区摘要（全局）回答跨文档、全局性问题。',
        assembly: '索引期：LLM 抽取实体/关系/声明 → 建图 → 社区检测 → 逐层生成社区摘要（索引成本高昂，是普通嵌入的数十倍 token）；查询期：local search（实体邻域）+ global search（社区摘要 map-reduce）。',
        observability: '图本身是可视化资产（实体、关系可浏览）；但 LLM 抽取质量难审计——图里的错边比坏 chunk 更隐蔽。',
        customization: '抽取 prompt、社区层级、遍历策略均可调；工程链路长，调优面广。',
        costOps: '成本大头在索引期 LLM 调用与图的增量更新（文档变更→局部重抽取是难题）；Neo4j 路线另加图库运维。',
        compliance: '自托管可控；注意抽取过程会把全量语料过一遍 LLM——用云模型时等于数据出域。',
        pmTakeaway: 'PM 决策点是问题类型学：用户问「X 条款是什么」→ 向量够了；问「这批合同里哪些供应商之间有关联风险」→ 只有图能答。先分析问题分布，再决定是否值得付图的索引税。',
        strengths: ['全局性、跨文档、多跳问题的唯一系统解', '图资产可复用（可视化、审计、BI）', '社区摘要提供「整体是什么」的能力'],
        weaknesses: ['索引成本高（LLM 抽取 token 量巨大）', '增量更新困难', '抽取错误难发现、难修复'],
        whenToPick: '问题分布里全局/关系类占比可观、语料相对稳定、且愿意为索引期成本买单时。',
        vsForge: 'Forge 的 graph_query 节点是 fallback（未接图库，执行时共享稠密结果）——目录里保留它是为了讲清这条路线的位置，画布上能装配出图增强的形态，Trace 会诚实告诉你它没干活。真要走图路线，去看 Microsoft GraphRAG 或 Neo4j 的实现。',
      },
    ],
  },
]

export const LANDSCAPE_CONCLUSION: { title: string; points: string[] } = {
  title: 'PM 结论：什么时候买、什么时候建、什么时候用本工作台',
  points: [
    '买（托管套件）：检索不是产品差异化点、数据出域可接受（或云边界可接受）、上线时间 < 一个季度。选型顺序看既有云：Azure→AI Search，AWS→Kendra/Bedrock KB，GCP→Vertex；纯验证用 OpenAI File Search 一天出结论。验收时必须写进合同的三件事：坏 case 归因通道、权限过滤行为、成本模型上限。',
    '建（开源编排 + 检索中台）：数据不能出域、检索质量是产品核心、或需要深度定制（行业切分、私有重排）。默认组合：LlamaIndex/Haystack + 已有 ES 则 hybrid / 无基建则 Qdrant 类向量库 + LangSmith/Langfuse 观测。走向 Agent 化选 LangGraph；文档版式复杂加 RAGFlow 类解析；全局关系问题占比高再评估 GraphRAG。',
    '用本工作台（设计沙盘，非生产引擎）：在买/建决策之前，用它把候选链路装配出来、跑 Trace、写验收标准——「重排该带来什么可测量的收益」「安全门该挡什么」在沙盘里先想清楚，再去花钱。它的占位节点此时反而是优点：架构讨论不被具体实现绑架。明确不该用它的场景：接真实客户数据、SLA 承诺、多租户——它没有 KB 隔离、算法面是 Naive+、安全门是正则，这些都写在画布的徽标上。',
  ],
}
