import type { StageLesson } from './types'

// 环节拆解：流水线每一环的「产品规格级」说明。
// 每个环节覆盖：目的、对质量/时延/成本/风险的影响、可调旋钮、
// 在本仓库如何装配、动力（为什么存在/缺了会怎样/过度会怎样）、live vs stub、面试追问。
// 键 = 后端 NODE_CATALOG 的节点类型；_ 前缀是没有画布节点的系统级环节。
// tests/test_interview_content.py 校验这里覆盖了后端目录的全部节点类型。

export const STAGES_INTRO: string[] = [
  '这张地图按真实流水线排列：上面一条是摄取线（文档怎么进来），下面一条是查询线（问题怎么被回答），加上横切件与系统级环节。点击任何环节：若当前画布上有对应节点会直接选中（右侧检查器同时给讲解和可改配置）；没有的话讲解显示在下方，还可以一键把节点加进画布试装。',
  '读法建议：每个环节先看「动力」——为什么这一环存在、缺了会怎样、过度设计会怎样。面试里能把动力讲清，比背出十个组件名有说服力得多。',
]

export const STAGE_LESSONS: Record<string, StageLesson> = {
  // ============ 摄取线 ============
  parse_route: {
    nodeType: 'parse_route',
    title: '上传与解析路由',
    lane: 'ingest',
    purpose: '识别上传文件的真实类型（按文件签名而非扩展名），把字节流交给正确的解析器。这是数据面质量的第一道闸门。',
    impact: {
      quality: '决定性：路由错一次，下游全错——扫描版 PDF 被当纯文本解析会产出空 Block，索引里是垃圾，两周后才在坏答案里暴露。',
      latency: '摄取期一次性开销，毫秒级；对查询时延零影响。',
      cost: '本身近零成本，但路由错误的返工成本（重解析、重索引）很高。',
      risk: '无声失败是最大风险——所以本仓库让每次路由决策带置信度与 reason_codes，写进 Ingest Trace。',
    },
    knobs: [
      { name: 'route', effect: 'auto 按签名自动选择；解析不对时可强制指定（pdf_page_text / office_structure / tabular…）后 reprocess。', effective: true },
    ],
    assembly: '左轨「数据」页上传文件，上传前可在「解析路由」下拉里强制路由；上传后看底部「Ingest Trace」的 route 行——置信度与 reason_codes 就是决策依据。选中 Custom Document Parsing Recipe 里的 route 节点也可改默认路由。',
    dynamics: {
      why: '企业文档格式是长尾分布（PDF、Office、CSV、HTML、扫描件…），单一解析器不可能全对。路由把「格式识别」显式化成可审计的决策。',
      ifMissing: '所有文件走同一解析器：格式不符时要么报错（用户体验差）要么产出坏文本（更糟，无声污染索引）。',
      ifOverdone: '为每种子格式建独立路由分支、上版面分析模型，摄取时延与运维成本飙升——文档类型单一的场景不需要。',
    },
    liveStatus: 'live：签名检测与路由真实执行。但注意 PDF 的 layout 路由是轻量近似，不是真正的版面分析（RAGFlow 类引擎才有）。',
    interviewQs: [
      { q: '为什么按文件签名而不是扩展名路由？', a: '扩展名会撒谎：改名的 .doc、伪装成 .txt 的 CSV 很常见。签名（magic bytes）看文件真实结构。reason_codes 记录判断依据，路由错了可以追认知，而不是只能重试。' },
      { q: '解析质量怎么验收？', a: '两个抓手：Ingest Trace 的 blocks/chunks 数量是否符合直觉（40 页 PDF 出 3 个 block 就有问题）；抽样对照 Block 内容与原文。生产上应加自动告警：置信度低于阈值的路由决策进人工复核队列——本仓库还没做这个队列，是诚实的欠账。' },
    ],
  },
  native_parser: {
    nodeType: 'native_parser',
    title: '文本 / Markdown 解析',
    lane: 'ingest',
    purpose: '把 Markdown、纯文本按标题层级切成结构化 Block，保留 heading_path（标题路径）。',
    impact: {
      quality: '标题层级保留得好，后续 Chunk 的语义边界就自然；heading_path 进 metadata 后引用可读性大增（「退款政策 > 特殊情形」比「chunk 37」有用得多）。',
      latency: '毫秒级。',
      cost: '近零。',
      risk: '低——文本解析是确定性逻辑。',
    },
    knobs: [{ name: '（无参数）', effect: '质量取决于原文结构是否清晰；写知识库文档时用好标题层级本身就是数据治理。', effective: true }],
    assembly: '无需手动装配：上传 .md/.txt 时由 parse_route 自动路由到达。看 Ingest Trace 的 parse 行确认。',
    dynamics: {
      why: '结构是免费的语义信号，扔掉标题层级等于把作者已经做好的信息组织丢弃。',
      ifMissing: '整篇文档变成无结构长文本，Chunk 边界只能按字数硬切，跨段落切断率上升。',
      ifOverdone: '过度解析（比如把每个列表项都拆成独立 Block）会让 Chunk 碎片化，检索命中一堆无上下文的短句。',
    },
    liveStatus: 'live：真实执行。',
    interviewQs: [{ q: '知识库源头该怎么配合解析器？', a: '这是 PM 能推动的最高杠杆之一：制定文档规范（标题层级、每节自包含、关键术语显式写出）比任何检索算法优化都便宜。RAG 质量问题有一半其实是内容治理问题。' }],
  },
  pdf_parser: {
    nodeType: 'pdf_parser',
    title: 'PDF 解析',
    lane: 'ingest',
    purpose: '按页提取 PDF 文本层，每页一个 Block 并记录页码——页码是后续引用定位的关键 metadata。',
    impact: {
      quality: 'PDF 是企业文档的主战场也是重灾区：双栏排版行序错乱、表格拍平、扫描件无文本层。解析质量直接决定这批文档可用不可用。',
      latency: '摄取期与页数线性相关。',
      cost: '低（不调模型）；若上 OCR/版面分析则成本上一个量级。',
      risk: '扫描件无文本层时产出空 Block——必须在 Ingest Trace 里可见，而不是无声跳过。',
    },
    knobs: [{ name: '（无参数）', effect: '扫描件需要 OCR，本框架未内置——这是显式的能力边界。', effective: true }],
    assembly: '上传 PDF 自动路由到达。验证方式：上传后看 Ingest Trace 的 blocks 数是否≈页数。',
    dynamics: {
      why: '合同、报告、政策文件大量以 PDF 存在，绕不开。',
      ifMissing: '放弃 PDF 等于放弃多数企业场景。',
      ifOverdone: '给全部 PDF 上多模态版面模型：成本与时延暴涨，而其中 80% 可能是文本层完好的简单文档——应该按路由分层处理。',
    },
    liveStatus: 'live：按页取文本层真实执行。不做版面分析、不做 OCR、表格会拍平——三条边界都标注在节点说明里。复杂版式需求见方案对比里的 RAGFlow。',
    interviewQs: [{ q: '双栏 PDF 乱序怎么办？', a: '短期：把这类文档路由到人工预处理或换源头格式；中期：接版面分析引擎（成本可控的做法是只对路由置信度低的文档启用）。关键是先能发现——Ingest Trace 让「这篇解析得不对」在摄取当天可见，而不是两周后。' }],
  },
  office_parser: {
    nodeType: 'office_parser',
    title: 'Office 解析',
    lane: 'ingest',
    purpose: '从 DOCX/XLSX 的 Office XML 中结构化提取段落与表格行。',
    impact: {
      quality: 'Office XML 自带结构（段落、样式、表格），提取质量天然高于 PDF；嵌入图片与图表不提取是明确损失。',
      latency: '摄取期毫秒到秒级。',
      cost: '近零。',
      risk: '低。',
    },
    knobs: [{ name: '（无参数）', effect: '无可调项。', effective: true }],
    assembly: '上传 .docx/.xlsx 自动路由到达。',
    dynamics: {
      why: '企业内部知识（制度、流程、报表）大量存在于 Office 文件。',
      ifMissing: '同 PDF——放弃主流格式等于放弃场景。',
      ifOverdone: '解析嵌入对象（图表、SmartArt）投入产出比低，除非业务证明这些内容常被提问。',
    },
    liveStatus: 'live：真实执行。图片/图表内容不提取。',
    interviewQs: [{ q: 'Excel 里的知识怎么进 RAG？', a: '按行转文本 Block 并带上表头上下文（tabular 路由的做法）。但要诚实：数值型分析类问题（「Q3 哪个大区增长最快」）RAG 检索答不好——那是 Text-to-SQL/BI 的领域，PM 要会把这类问题划出 RAG 边界。' }],
  },
  tabular_parser: {
    nodeType: 'tabular_parser',
    title: '表格解析',
    lane: 'ingest',
    purpose: '把 CSV/XLSX 的每一行转成带表头上下文的文本 Block，让「按行检索」成为可能。',
    impact: {
      quality: '带表头是关键设计：没有表头的行文本（「张三, 8000, 华东」）几乎不可检索；带上（「姓名:张三 额度:8000 大区:华东」）就能被语义召回。',
      latency: '与行数线性相关。',
      cost: '超宽表会产出很长的行文本，推高嵌入 token 成本。',
      risk: '注意与 Chunk 大小配合：一行超过 max_chars 会被切断。',
    },
    knobs: [{ name: '（无参数）', effect: '无可调项；表格质量治理在源头。', effective: true }],
    assembly: '上传 .csv 自动路由到达；看 Ingest Trace 确认每行成 Block。',
    dynamics: {
      why: 'FAQ 表、价格表、规则表是知识库高频形态，按行检索比整表检索精准得多。',
      ifMissing: '整个 CSV 变成一个巨大文本块，任何按行的问题都召回整表噪声。',
      ifOverdone: '对分析型大宽表逐行嵌入：几十万行 = 几十万向量，成本高而问答价值低——这类数据该走结构化查询。',
    },
    liveStatus: 'live：真实执行。',
    interviewQs: [{ q: '什么表格适合进 RAG，什么不适合？', a: '判据是问题类型：查询单行事实（「X 产品保修几年」）适合；跨行聚合计算（求和、排名）不适合，应路由到 SQL 类工具。意图路由节点的设计动机之一正是把这两类问题分流——虽然它现在还是占位。' }],
  },
  _block_model: {
    nodeType: '_block_model',
    title: 'Block 数据模型（解析产物）',
    lane: 'ingest',
    purpose: 'Block 是解析器的输出单位：一段带类型（heading/paragraph/table_row/page）与位置信息（heading_path、页码）的结构化文本。它是「原文」与「检索单位 Chunk」之间的中间层。',
    impact: {
      quality: 'Block 层保留结构语义，让 Chunker 可以「沿结构边界切」而不是盲切字数；也让父块扩展（parent_expansion）这类设计在数据模型上成为可能。',
      latency: '无查询期影响。',
      cost: '存储翻倍（原文 + Block + Chunk 三层都存），换可追溯性。',
      risk: '无 Block 层的系统里，「这个 Chunk 来自原文哪里」无法精确回答——引用定位靠猜。',
    },
    knobs: [{ name: '（数据模型，无运行时旋钮）', effect: '结构由解析器决定。', effective: true }],
    assembly: '它不是画布节点，是解析器与 Chunker 之间的数据契约。观察方式：上传文档后 Ingest Trace 的 parse 行报告 Block 数量与类型分布。',
    dynamics: {
      why: '直接从原文切 Chunk 会丢结构；直接把 Block 当检索单位又粒度失控（一页 PDF 可能 3000 字）。两层分离让「保结构」和「控粒度」各自解决。',
      ifMissing: 'Chunk 与原文之间没有锚点，重切分（改 chunk 参数后 reprocess）无法保持引用稳定性。',
      ifOverdone: '给 Block 建过多类型与属性会让每个新解析器的接入成本上升——本仓库刻意只留了最小集合。',
    },
    liveStatus: 'live：Block 持久化在 SQLite（真相源），带 source 版本与 SHA-256。这是「Qdrant 可整体重建」的前提——向量丢了，Block 还在。',
    interviewQs: [{ q: '为什么不直接「原文→Chunk」两层了事？', a: '三层（原文→Block→Chunk）的价值在变更管理：改切分策略只需从 Block 重切，不用重新解析；引用可以定位到 Block 级（页码/标题路径）；解析质量问题与切分质量问题可以分开归因。数据模型上的这一层分离，是后面一切「可证明」的地基。' }],
  },
  chunker: {
    nodeType: 'chunker',
    title: 'Chunk 切分',
    lane: 'ingest',
    purpose: '把 Block 切成检索粒度的 Chunk（默认约 1200 字符、120 重叠）。Chunk 是检索、引用、嵌入的最小单位——这一刀切在哪，决定整个系统「看世界的分辨率」。',
    impact: {
      quality: '整条流水线影响质量的第一大参数。太大：向量语义被稀释（一个向量代表三个主题等于哪个都不代表），召回变糊；太小：命中了但上下文残缺，模型拿到半句话。',
      latency: '间接影响：Chunk 越小索引里向量越多，检索规模变大。',
      cost: 'Chunk 数 × 嵌入单价 = 索引成本；重叠比例直接放大这个数（10% 重叠 ≈ 10% 多付）。',
      risk: '切断句子/表格行会制造「看起来相关但读不通」的证据，比没召回更迷惑人。',
    },
    knobs: [
      { name: 'max_chars', effect: '单 Chunk 上限。经验起点：FAQ 类 400-800，政策条文 800-1500，叙事文档 1200-2000。', effective: true },
      { name: 'overlap', effect: '相邻 Chunk 重叠区，缓解切断伤害。常用 10%~15% of max_chars。', effective: true },
    ],
    assembly: '左轨「装配」选 Custom Document Parsing → 点 chunk 节点 → 检查器改 max_chars/overlap → 保存草稿 → 「数据」页对已有文档点 reprocess 或重新上传。Ingest Trace 的 chunk 行会显示生效参数与产出数量——改前改后跑两次对比，这是本工作台最直观的实验。',
    dynamics: {
      why: '嵌入模型与上下文窗口都需要有界输入；引用需要有界证据。「无限上下文」不能免除切分——成本与注意力稀释仍在。',
      ifMissing: '整篇文档一个向量：长文档的向量是所有主题的平均，专指性问题全部召回失败。',
      ifOverdone: '上语义切分、Agent 切分等重型方案前先问：朴素滑窗 + 结构边界的基线分数是多少？没有评测就上高级切分，是最常见的过度设计。',
    },
    liveStatus: 'live：max_chars/overlap 真实生效于上传与 reprocess。当前是「结构感知的滑窗」（沿 Block 边界），没有语义切分——够诚实基线用。',
    interviewQs: [
      { q: 'chunk 大小到底怎么定？给个方法而不是数字。', a: '方法论四步：① 看内容形态（自包含短条目→小 chunk；论证链长→大 chunk）；② 看嵌入模型有效输入长度（超过后语义质量衰减）；③ 建 20 条黄金问答，扫参数跑 Hit@5；④ 用重排兜底粒度失配（粗召回可以容忍偏大 chunk）。任何脱离评测报出来的「最佳值」都是运气。' },
      { q: '重叠是不是越大越好？', a: '不是。重叠治的是「答案恰好横跨边界」这一种病，10-15% 通常够；再大就是花钱买冗余，还会让相邻 Chunk 向量趋同、Top-K 里挤满近重复内容，挤掉真正多样的证据。' },
    ],
  },
  metadata_enricher: {
    nodeType: 'metadata_enricher',
    title: 'Metadata 富化',
    lane: 'ingest',
    purpose: '把 heading_path、页码、Block 类型、来源文档版本写入每个 Chunk 的 metadata——给后续过滤、引用定位、权限控制留下抓手。',
    impact: {
      quality: '不直接提升召回分数，但决定「召回结果可不可用」：metadata 是过滤（版本/日期/部门）与可读引用的原料。',
      latency: '近零。',
      cost: '存储与 payload 体积略增。',
      risk: 'metadata 缺失是隐性债务：等到需要「只查现行版政策」时才发现没存生效日期，全库重摄取。',
    },
    knobs: [{ name: '（无参数）', effect: '进阶做法是 LLM 生成摘要/标签/假设问题（本仓库未实现，诚实标注）。', effective: true }],
    assembly: 'Custom Document Parsing Recipe 里的 meta 节点；上传后在结果证据条目里展开可看到 metadata。',
    dynamics: {
      why: '检索是「语义相似 + 结构约束」的交集，metadata 承载结构约束的一半。企业场景（版本、密级、部门）尤其依赖。',
      ifMissing: 'metadata_filter 无从过滤，引用只能显示 chunk_id 而不是「退款政策 > 第 3 节 · 第 2 页」。',
      ifOverdone: '用 LLM 给每个 Chunk 生成十个标签：索引成本翻几倍，而多数标签从未被查询使用。先确认过滤需求再富化。',
    },
    liveStatus: 'live：基础 metadata（heading_path/页码/类型）真实保存。无 LLM 增强。',
    interviewQs: [{ q: 'metadata 设计的 PM 检查单？', a: '四问：谁会按什么维度过滤（版本/日期/权限/产品线）？引用展示需要什么字段？合规审计需要什么字段？——以及最重要的：这些字段源头有没有？源头没有的字段，技术再好也富化不出来，要回头推动内容治理。' }],
  },
  embed_index: {
    nodeType: 'embed_index',
    title: 'Embedding 与索引写入',
    lane: 'ingest',
    purpose: '调用 Embedding 模型把每个 Chunk 变成向量，写入 Qdrant（point id 与 chunk_id 对齐，metadata 作为 payload 同写）。',
    impact: {
      quality: '嵌入模型决定「语义相似」的定义——它认为不像的，后面谁都救不回来。查询侧与索引侧必须同模型，这是硬约束。',
      latency: '摄取期批量调用；服务不可用时本仓库降级 deferred（暂缓）而不是失败。',
      cost: '嵌入调用是摄取成本大头；换模型 = 全量重嵌入，是最贵的一类变更。',
      risk: '新旧模型向量混在一个 collection 里不可比——分数全是噪声。所以「换模型必须重建索引」是纪律不是建议。',
    },
    knobs: [
      { name: 'model_ref', effect: '绑定注册过的 Embedding 模型；上传时选择的 Embedding 会覆盖此项。', effective: true },
      { name: 'collection', effect: '当前固定使用配置的 collection——单 collection、无 KB 隔离是已知设计债。', effective: false },
    ],
    assembly: '「模型」页注册 Embedding 端点 → 「数据」页上传时选择该模型；Qdrant/模型不可用时 Ingest Trace 的 index 行显示 deferred，就绪后点「重建索引」补齐。',
    dynamics: {
      why: '语义检索的全部前提。',
      ifMissing: '只能词法检索——本仓库的 lexical_fallback 演示了这个退化态长什么样。',
      ifOverdone: '盲目追嵌入榜单换大模型：维度更高存储更贵、全量重嵌一次，而你的领域评测可能根本测不出差异。先建评测再换模型。',
    },
    liveStatus: 'live：真实调用 OpenAI 兼容 Embedding 端点并写 Qdrant；不可用时 deferred，真相源（SQLite）不受影响——文档永远不会因为索引服务挂了而丢。',
    interviewQs: [
      { q: 'deferred 设计的产品含义？', a: '把「文档安全」和「索引就绪」解耦成两个状态。用户上传永远成功（真相源落库），索引是可重试的派生操作。反面设计是上传因 Qdrant 超时而失败——用户重传三次、库里三份副本。这是「真相源 vs 派生索引」架构观在交互层的直接体现。' },
      { q: '嵌入服务的成本怎么估？', a: '索引成本 = chunk 数 × 平均 token × 单价，一次性但随语料增长；查询成本 = QPS × 查询 token × 单价，持续发生。自托管开源模型后成本结构变成 GPU 固定成本——语料大、QPS 高时自托管拐点很快到来。' },
    ],
  },

  // ============ 查询线 ============
  question: {
    nodeType: 'question',
    title: '问题入口',
    lane: 'query',
    purpose: '查询链路的入口节点，携带用户问题文本。看似平凡，实际是「查询理解」全部未来能力（改写、扩展、分解）的挂载点。',
    impact: {
      quality: '用户问题的质量方差极大（错字、口语、复合问题），入口不做任何归一化时，这些方差全部传导给检索。',
      latency: '零。',
      cost: '零。',
      risk: '高风险措辞会在下游触发安全门拒答（设计行为）。',
    },
    knobs: [{ name: '（无参数）', effect: '问题文本在底部控制台输入。', effective: true }],
    assembly: '每条查询 Recipe 的起点；底部控制台的问题框就是它的输入。',
    dynamics: {
      why: 'DAG 需要显式入口；把「原始问题」做成节点，才能在它后面插入意图路由、改写等处理而不破坏结构。',
      ifMissing: '（不可缺。）',
      ifOverdone: '在入口塞太多前处理（多轮改写、多路扩展）：每步都是一次 LLM 调用，时延与成本翻倍，先证明收益。',
    },
    liveStatus: 'live：透传问题文本。',
    interviewQs: [{ q: '多轮对话的上下文在哪处理？', a: '诚实回答：本仓库是单轮问答，没有对话状态管理。生产做法是在入口前加「基于对话历史的问题重写」（把「那第二种呢？」改写成自包含问题）——这也是为什么入口要是显式节点：好挂前处理。' }],
  },
  intent_router: {
    nodeType: 'intent_router',
    title: '查询理解 / 意图路由',
    lane: 'query',
    purpose: '设计目标：判断问题类型（事实查询/操作指引/闲聊/越界请求），路由到不同检索分支或直接短路（闲聊不必检索）。',
    impact: {
      quality: '对混合流量提升显著：闲聊走轻路径、精确编号类问题走关键词路径、复杂问题走完整链路。',
      latency: '增加一次分类调用（小模型可做到几十 ms）；但为多数简单请求省下整条重链路。',
      cost: '同上——路由本身花小钱，为省大钱。',
      risk: '错误路由是新的失败模式：把事实问题误判为闲聊直接不检索，比检索差更糟。需要路由准确率监控。',
    },
    knobs: [{ name: '（当前配置均不生效）', effect: '占位节点。', effective: false }],
    assembly: 'v0_3_intent Recipe 里可看到它的位置（question 之后、检索之前）。加载后选中 intent 节点，检查器徽章明确标注「占位」。',
    dynamics: {
      why: '真实流量不是均匀的「好问题」，路由让不同问题走成本与能力匹配的路径。',
      ifMissing: '所有流量走同一条重链路：简单问题浪费成本，特殊问题得不到特化处理。',
      ifOverdone: '意图类目切得过细（20 个意图）：分类准确率崩、维护成本高。从 3-4 个粗类起步。',
    },
    liveStatus: 'stub 占位直通：未实现意图分类，仅在 Trace 记录经过（stub_passthrough）。画布上摆了它 ≠ 有意图识别——这是「目录能力 ≠ 已实现能力」的第一个例子。',
    interviewQs: [{ q: '如果实现它，你会怎么设计 MVP？', a: '三分类起步（可检索问答 / 闲聊寒暄 / 需要人工），用小模型或甚至规则做，把分类结果写进 Trace 供审计；上线后先只做「闲聊短路」这一个动作（风险最低收益直接），路由准确率有数据后再扩展分支。' }],
  },
  metadata_filter: {
    nodeType: 'metadata_filter',
    title: '元数据过滤',
    lane: 'query',
    purpose: '设计目标：按 metadata（版本、生效日期、部门、密级）在检索前缩小候选范围——政策问答与权限场景的刚需。',
    impact: {
      quality: '对「必须查现行版」类问题是对错问题而非分数问题：过滤缺失时旧版政策混进证据，答案可能合规错误。',
      latency: '带过滤的向量检索略慢，但远好于检索后再丢弃（后过滤会导致有效结果不足 k 条）。',
      cost: '近零。',
      risk: '过滤条件过严导致零召回——所以设计里有 on_empty 策略（fallback_once：放宽一次重试）。',
    },
    knobs: [
      { name: 'fields / on_empty', effect: '过滤字段与空结果策略。当前均不生效（占位）。', effective: false },
    ],
    assembly: 'v0_3_intent Recipe 里的 filter 节点。真实实现时会落到 Qdrant 的 payload 预过滤（见向量库专章「过滤与 payload」节）。',
    dynamics: {
      why: '语义相似回答不了「哪个版本有效」——这是结构约束，必须用 metadata 表达。',
      ifMissing: '过期政策、越权内容进入证据。这正是本仓库明确声明「不宜接真实合规场景」的直接原因之一。',
      ifOverdone: '把过滤当检索用（几十个 AND 条件）：命中率崩塌，用户永远得到「没有证据」。',
    },
    liveStatus: 'stub 占位直通：过滤条件不会真正作用于候选集。合规场景的硬前提尚未实现——这条必须写在任何对外声明里。',
    interviewQs: [{ q: '预过滤和后过滤差在哪，为什么重要？', a: '预过滤在 ANN 搜索时就带条件（Qdrant 的 filtered HNSW），保证返回满 k 条合格结果；后过滤先取 Top-K 再删不合格的，可能删完只剩 1 条甚至 0 条。权限场景必须预过滤——后过滤等于「先看到再假装没看到」，审计过不了。' }],
  },
  dense_retrieve: {
    nodeType: 'dense_retrieve',
    title: '稠密检索（向量召回）',
    lane: 'query',
    purpose: '把问题用同一个 Embedding 模型向量化，在 Qdrant 里找最近邻 Chunk。本链路真实的召回主力。',
    impact: {
      quality: '召回的天花板：这里没捞到的证据，后面所有环节都救不回来。语义泛化是它的强项（措辞不同也能命中），精确 token 匹配是弱项。',
      latency: '两段：查询嵌入调用（几十 ms~）+ ANN 检索（毫秒级）。嵌入调用通常是大头。',
      cost: '每次查询一笔嵌入费用 + 向量库常驻资源。',
      risk: '两个降级态都在 Trace 里可见：Qdrant/嵌入不可用时退化为词法重叠检索（backend=lexical_fallback）。',
    },
    knobs: [
      { name: 'top_k', effect: '候选条数。节点配置优先于请求参数——这是「Recipe 即真相」原则的体现。', effective: true },
      { name: 'score_threshold', effect: '低于阈值的命中被丢弃。设太高会滤光全部候选，退化成「没有证据」。', effective: true },
      { name: 'model_ref', effect: '查询侧必须与索引侧同模型，暂不支持单独切换（标注不生效）。', effective: false },
    ],
    assembly: '选中画布 dense_retrieve 节点改 top_k/threshold，保存草稿后运行；Trace 该行显示 backend（qdrant_dense 或 lexical_fallback）、top_k、候选数与分数。这是全工作台最值得反复做的实验节点。',
    dynamics: {
      why: '语义召回是 RAG 相对关键词搜索的核心增量——用户不知道文档原文用词时依然能命中。',
      ifMissing: '退回纯关键词检索，措辞鸿沟（「莫名扣款」vs「未经授权的交易」）无法跨越。',
      ifOverdone: 'top_k 拉满 + 无重排：噪声灌进 Prompt，长上下文的注意力稀释让答案变差、成本变高——「多召回」不等于「好答案」。',
    },
    liveStatus: 'live：优先 Qdrant 向量检索，真实执行；不可用时词法回退并在 Trace 标注 fallback_lexical。徽标、Trace、行为三方一致。',
    interviewQs: [
      { q: '怎么向业务方解释「为什么这条没被召回」？', a: '给三层归因：① 它在不在索引里（查真相源与索引状态）；② 它的相似分排第几（把 top_k 临时放大看它在不在第 6-20 名）；③ 分数为什么低（措辞鸿沟→考虑改写或混合检索；chunk 太大语义稀释→调切分）。Trace 提供①②的现场证据，这就是可观测性对 PM 的直接价值。' },
      { q: 'score_threshold 有什么用，怎么定？', a: '它是「宁可不答也不瞎答」的第一道闸：全部候选分数都低说明库里没有相关内容，不如诚实说不知道。定法：用评测集画「分数-正确率」曲线找拐点。没有评测就拍阈值，等于随机拒答。' },
    ],
  },
  sparse_retrieve: {
    nodeType: 'sparse_retrieve',
    title: '稀疏检索 / BM25',
    lane: 'query',
    purpose: '设计目标：关键词/学习型稀疏向量召回，与稠密检索互补——精确 token 匹配（产品型号、法条编号、人名）是它的主场。',
    impact: {
      quality: '混合检索（dense+sparse）在多数企业评测上稳定优于单路，因为两者的失败模式互补：dense 输在精确匹配，sparse 输在措辞泛化。',
      latency: '倒排检索本身毫秒级，快于向量路。',
      cost: '需要第二套索引（倒排或命名稀疏向量），存储与摄取双写成本。',
      risk: '双索引一致性是长期运维税：文档更新时两边必须同步。',
    },
    knobs: [{ name: 'top_k', effect: '当前被记录但不产生独立候选集（占位）。', effective: false }],
    assembly: 'v0_2_hybrid Recipe 展示了它的位置（与 dense 并行、汇入 RRF）。运行后看 Trace：它的 execution 是 fallback_shared_dense——共享稠密结果，没有独立召回。',
    dynamics: {
      why: '用户查「条款 4.2.1」「型号 X200」时，向量检索给你语义上「差不多」的内容，而用户要的是「就这个」。',
      ifMissing: '精确匹配类问题系统性偏弱——本仓库当前正处于这个状态，评测里应该能看到这类 case 的失败。',
      ifOverdone: '为占比 2% 的精确查询建整套双索引：先用评测确认这类问题的真实占比再投入。',
    },
    liveStatus: 'fallback 退化：无独立稀疏索引，执行时共享稠密/词法结果，Trace 如实标注。这是本仓库算法面最该优先补的第一块（配合 RRF 一起）。',
    interviewQs: [{ q: '实现它你会选什么方案？', a: '两条路：已有 ES/OpenSearch → 直接用 BM25（运维复用）；没有 → Qdrant 命名稀疏向量（SPLADE 类学习型稀疏），单库双路省掉一致性问题。决策关键是运维归属而不是算法分数——这是 PM 视角与算法视角的典型分歧点。' }],
  },
  rrf_fusion: {
    nodeType: 'rrf_fusion',
    title: 'RRF 融合',
    lane: 'query',
    purpose: '设计目标：Reciprocal Rank Fusion 合并多路召回——只用名次不用分数（score = Σ 1/(k+rank)），天然解决「向量分数与 BM25 分数量纲不可比」的问题。',
    impact: {
      quality: '融合让「任一路排名靠前」的证据都有机会进入最终候选，是混合检索收益的收口环节。',
      latency: '纯计算，微秒级，几乎免费。',
      cost: '零。',
      risk: '低——RRF 无需调参训练，是融合算法里最稳健的默认选择。',
    },
    knobs: [{ name: 'k（平滑常数，惯例 60）', effect: '控制头部名次的权重差异。当前不生效（占位）。', effective: false }],
    assembly: 'v0_2_hybrid 里的 f 节点，两路 candidates 汇入。当前只有一路真实候选，融合是空转——Trace 标 stub_passthrough，证据顺序不变。',
    dynamics: {
      why: '不同检索器的分数不可直接比较（余弦∈[-1,1]，BM25 无上界），拿分数加权是常见错误；名次是唯一公平的共同语言。',
      ifMissing: '多路召回没法合并，混合检索无从谈起。',
      ifOverdone: '在 RRF 之上叠加学习型融合模型（LTR）：需要点击/标注数据，知识库场景通常没有——RRF 够用是共识。',
    },
    liveStatus: 'stub 占位直通：没有第二路候选可融合。它的实现依赖稀疏检索先落地——依赖关系本身就是排期讲解的好素材。',
    interviewQs: [{ q: '为什么用名次不用分数融合？', a: '分数量纲不可比且分布随语料漂移；名次是序数信息，稳定且免调参。RRF 的 1/(k+rank) 形式还让「一路第 1 + 另一路第 50」不会输给「两路都第 10」太多——鲁棒性正是生产要的性质。' }],
  },
  reranker: {
    nodeType: 'reranker',
    title: '重排（Cross-Encoder）',
    lane: 'query',
    purpose: '设计目标：用交叉编码器对粗召回的 candidate_k 条做「问题×文档」联合精排，输出 final_k 条证据。生产 RAG 里通常是单点精度收益最大的模块。',
    impact: {
      quality: '双编码器（各自独立编码）注定丢失交互信息；交叉编码器逐 token 交叉注意力，相关性判断准一个档次。典型收益：把「答案在第 8 名」变成「答案在第 1 名」。',
      latency: '主要代价：每条候选跑一次模型前向，50 条候选可能加几百 ms。',
      cost: '重排模型推理费用（托管 API 按条计费，或自托管 GPU）。',
      risk: '召回没捞到的它救不了——它是精排不是召回；候选池太小时收益归零。',
    },
    knobs: [
      { name: 'model_ref / candidate_k / final_k', effect: '设计上是「粗进精出」（如 50 进 6 出）。当前均不生效（占位）。', effective: false },
    ],
    assembly: 'v0_4_rerank Recipe 里的 r 节点（fusion 之后、context 之前）。占位证明实验：跑 v0_1_dense 和 v0_4_rerank 各一次，对比证据顺序完全一致 → 重排没有发生。',
    dynamics: {
      why: '召回追求「别漏」（高召回率），精排追求「排对」（高精确率）——一个模块同时优化两个目标必然平庸，分两级是检索工程的基本功。',
      ifMissing: '只能靠嵌入相似分排序，Top-5 里混进「主题相关但答非所问」的内容，直接传导为答案质量问题。',
      ifOverdone: 'candidate_k 开太大（500 条）：时延与费用线性上涨，而第 100 名之后基本不含答案；用生成式大模型做 listwise 重排：贵一个量级，先证明 cross-encoder 不够用。',
    },
    liveStatus: 'stub 占位直通：未调用任何模型，证据保持召回顺序。为什么还没做：没有稀疏检索与评测基线时，重排收益无法测量——我拒绝上一个测不出收益的模块，这个顺序判断本身是产品决策（详见「Rerank 的产品价值」深讲章）。',
    interviewQs: [
      { q: '为什么不先做重排？它不是收益最大吗？', a: '收益最大是「在有评测的前提下测出来的」。我的排序是：先评测（尺子）→ 再混合检索（扩召回池）→ 再重排（精排池内排序）。在只有单路 dense 且 top_k=5 的现状下，重排的输入池太小，理论收益被截断。做事顺序也是产品设计。' },
      { q: '重排的成本怎么向管理层解释？', a: '换算成业务语言：每查询 +200ms 和 +0.x 分钱，换 Top-3 命中率 +15%（示例量级，以自家评测为准）——如果每次坏答案的人工兜底成本是 X 元，很容易算出盈亏平衡的查询量。重排是少数能这样干净算账的模块。' },
    ],
  },
  context_builder: {
    nodeType: 'context_builder',
    title: '上下文构建',
    lane: 'query',
    purpose: '设计目标：把证据装进有限的 Prompt 预算——按 token 预算截断、MMR 去冗余、按相关性排序拼装，并保持 [S#] 引用编号稳定。',
    impact: {
      quality: '同样的证据，不同的拼法答案不同：近重复证据挤占预算、关键证据被排在中部被注意力忽略（lost in the middle），都是这里管的。',
      latency: '纯计算，近零。',
      cost: '直接控制生成侧 token 成本——预算裁剪是成本闸门。',
      risk: '裁剪逻辑有 bug 时会静默丢证据，且比检索问题更难发现。',
    },
    knobs: [
      { name: 'token_budget / mmr_lambda', effect: '预算上限与「相关性 vs 多样性」权衡系数。当前均不生效（占位）。', effective: false },
    ],
    assembly: '几乎所有查询 Recipe 里都有 c 节点。当前证据原样透传，Prompt 长度实际由 top_k 控制——这一点节点说明里写明了。',
    dynamics: {
      why: '检索返回的是「候选集合」，生成需要的是「有预算的证据排版」，两者之间必须有个装配工。',
      ifMissing: '证据无序、无预算地灌进 Prompt：小则浪费钱，大则超窗被截断（最后一条证据被切一半）。',
      ifOverdone: '复杂的压缩式构建（LLM 先摘要每条证据再拼装）：又一次模型调用，且摘要可能丢关键细节、破坏引用对应关系——引用完整性优先于压缩率。',
    },
    liveStatus: 'stub 占位直通：无预算裁剪、无 MMR。诚实后果：top_k 开大时 Prompt 会线性变长，成本失控风险由使用者自己扛——工作台没有替你兜底。',
    interviewQs: [{ q: '证据顺序真的影响答案吗？', a: '有实证支持：模型对上下文头尾的注意力显著高于中部（lost in the middle）。所以构建器的经典策略是把最重要证据放开头和结尾。这也解释了为什么重排 + 构建器要成对出现：先排对，再摆对位置。' }],
  },
  parent_expansion: {
    nodeType: 'parent_expansion',
    title: '父块扩展（小检索大读取）',
    lane: 'query',
    purpose: '设计目标：用小 Chunk 检索（向量专指性好），命中后回捞其父级 Block/邻近上下文交给生成（阅读连贯性好）——「small-to-big」策略。',
    impact: {
      quality: '同时要到两头的好处：检索准 + 上下文全。对「答案分散在一节多个段落」的内容形态收益明显。',
      latency: '多一次真相源查询（按 chunk→block 索引回捞），毫秒级。',
      cost: 'Prompt 变长（父块比子块大），生成成本上升——要与 token 预算联动。',
      risk: '父块过大时把整页塞进去，重新引入噪声稀释。',
    },
    knobs: [{ name: '（当前配置不生效）', effect: '占位节点。', effective: false }],
    assembly: 'v0_5_context Recipe 展示其位置。数据模型已经为它铺好路：Chunk→Block 的层级关系在 SQLite 里存在，实现它只差执行器逻辑。',
    dynamics: {
      why: '「检索最优粒度」和「阅读最优粒度」天然不一致，父子结构让两者解耦。',
      ifMissing: '被迫在一个 chunk 大小上同时妥协检索与阅读。',
      ifOverdone: '层层上捞（chunk→节→章→全文）就回到了 V0 塞全文的老路。',
    },
    liveStatus: 'stub 占位直通：未实现回捞逻辑。',
    interviewQs: [{ q: '它和「把 chunk 调大」有什么区别？', a: '调大 chunk 是让一个向量代表更多内容——检索精度受损；父块扩展是检索用小向量、阅读用大文本——精度与上下文两者兼得。前者是妥协，后者是解耦，数据模型上多一层父子关系就是为此付的成本。' }],
  },
  llm_generate: {
    nodeType: 'llm_generate',
    title: 'LLM 生成',
    lane: 'query',
    purpose: '用检索证据约束生成回答，要求每个事实句标 [S#] 引用。RAG 里生成模型的角色是「阅读理解与组织语言」，不是「知识来源」。',
    impact: {
      quality: '决定答案的组织、语气与忠实度。指令遵循能力（会不会乖乖只用证据、标引用）比通用能力排名更重要。',
      latency: '整条链路的时延大头（秒级），流式输出是体感优化的第一手段（本仓库未做流式，诚实标注）。',
      cost: '按 token 计费的持续成本中心；上下文长度（top_k × chunk 大小）直接放大它。',
      risk: '幻觉与引用漂移。本仓库的兜底：引用对不上时 citation_repair 拦下，换成证据摘要；端点不可用时 extractive_fallback 降级为证据拼接。',
    },
    knobs: [
      { name: 'model_ref', effect: '绑定注册的 OpenAI 兼容 Chat 端点（LM Studio/vLLM/云服务均可）。', effective: true },
      { name: 'temperature', effect: '知识问答建议 0~0.2：要的是稳定复述证据，不是创意。', effective: true },
      { name: 'max_tokens', effect: '回答长度上限，也是成本闸门。', effective: true },
    ],
    assembly: '「模型」页注册 Chat 模型（填 base_url + model_name）→ probe 探测 → 选中 g 节点把 model_ref 绑上 → 运行。Trace 该行的 provider 字段说明真实发生了什么：openai_compatible_chat（真调了模型）或 extractive_fallback（降级摘要）。',
    dynamics: {
      why: '检索给证据，生成给「人话」——两者缺一不可，但责任必须分清：答案错了先查证据对不对，再查生成忠实不忠实。',
      ifMissing: '只能返回证据原文列表——事实上这正是 extractive_fallback 的行为，你可以断开模型体验一下「没有生成的 RAG」。',
      ifOverdone: '用旗舰大模型做简单 FAQ 复述：成本高一个量级而质量差异用户无感。模型分级路由（简单问题小模型）是成熟做法。',
    },
    liveStatus: 'live：真实调用 OpenAI 兼容端点，temperature/max_tokens/model_ref 真实生效；降级路径（extractive_fallback、citation_repair）也是真实实现并在 Trace 标注。',
    interviewQs: [
      { q: '怎么控制生成不瞎编？', a: '四层防御：Prompt 约束（只依据证据、逐句引用）；解码约束（低温度）；事后校验（citation_repair：引用对不上就不放行自由生成）；评测监控（引用忠实率作为核心指标）。单靠 Prompt 求模型「别编」是不够的，必须有校验闭环。' },
      { q: '模型选型 PM 该看什么？', a: '按优先级：指令遵循与引用格式的服从性 → 领域语言质量 → 时延（含流式）→ 成本 → 部署形态（数据能否出域）。通用榜单排名放最后——RAG 生成是「戴着镣铐跳舞」，镣铐服从性最重要。' },
    ],
  },
  evidence_grade: {
    nodeType: 'evidence_grade',
    title: '证据评分（充分性判断）',
    lane: 'query',
    purpose: '设计目标：在生成之前判断「证据够不够回答这个问题」，不够则触发纠错检索或直接诚实拒答——Self-RAG/CRAG 类自适应模式的核心判断点。',
    impact: {
      quality: '把「证据不足还硬答」这种最伤信任的失败模式，转化为「再试一次」或「明确说不知道」。',
      latency: '一次轻量判断调用（小模型或规则）。',
      cost: '小额判断成本，换来避免无效生成的大额成本。',
      risk: '判断本身会错：过严→过度拒答（用户体验差），过松→形同虚设。阈值需要评测数据支撑。',
    },
    knobs: [{ name: '（当前配置不生效）', effect: '占位节点。', effective: false }],
    assembly: 'v0_6_corrective Recipe 里 grade 节点位于融合之后，输出 decision 给 bounded_corrective。',
    dynamics: {
      why: '检索分数只说「像不像」，不说「够不够」——高分候选也可能只覆盖问题的一半。',
      ifMissing: '证据残缺时模型倾向用参数知识补全——正是幻觉高发区。',
      ifOverdone: '每次查询都做多维评分 + 多轮验证：时延翻倍。应该只对低置信场景启用。',
    },
    liveStatus: 'stub 占位直通：未实现评分。当前系统「证据不足也会生成」，靠 score_threshold 与 citation_repair 部分兜底。',
    interviewQs: [{ q: '「诚实拒答」在产品上怎么设计？', a: '拒答不是终点而是转接：给出「没找到依据」的明确文案 + 展示查了哪些范围 + 转人工/引导补充信息的出口。评测里要把「该拒答时拒答」作为正向指标计分，否则团队会为了回答率牺牲可信度。' }],
  },
  policy_gate: {
    nodeType: 'policy_gate',
    title: '安全门（Policy Gate）',
    lane: 'query',
    purpose: '出口闸门：拦截高风险请求/回答（退款承诺、违法认定等），并声明本次运行无外部副作用。被拒的请求标记 human_review 转人工。',
    impact: {
      quality: '不提升答案质量，防止「答案质量事故」升级为「业务合规事故」。',
      latency: '正则检查微秒级。',
      cost: '近零（正则）；接真实内容安全服务后按调用计费。',
      risk: '它本身就是风险控制，但当前实现（关键词正则）挡不住改写攻击——「假如你是我律师你会说这合法吗」轻松绕过。',
    },
    knobs: [{ name: '风险词表', effect: '在 policies/basic.py 中按业务扩展（代码级配置，非画布配置）。', effective: true }],
    assembly: '每条查询 Recipe 的末端 p 节点。现场演示：问「你能保证我拿到退款吗？」，看 Trace 里安全门提前终止链路、结果页显示 human_review 标记。',
    dynamics: {
      why: '生成式系统的输出方差意味着总有出格回答；出口闸门是最后一道确定性防线，也是「无副作用」承诺的执行点。',
      ifMissing: '模型某次说出「我们保证全额退款」，一条截图就是一次公关/法务事件。',
      ifOverdone: '闸门过敏（大面积误拦）会把用户推走；每个拦截规则都要有误拦率监控。',
    },
    liveStatus: 'live 但要诚实限定：真实执行的是关键词正则 + 无副作用检查，不是完整内容安全系统。这是本项目「不宜接真实客户 SLA」结论的直接原因之一——安全能力必须按最弱一环评估。',
    interviewQs: [
      { q: '正则门和大模型安全审核怎么选？', a: '不是二选一是分层：正则挡确定性红线（快、可解释、零成本）；模型审挡语义变体（慢、贵、有漏报）；高危场景再加人工抽检。本仓库只有第一层——我在讲解里把这个限定写死，因为夸大安全能力比没有安全能力更危险。' },
      { q: '「无副作用」声明是什么意思？', a: '这次运行没有调用任何会改变外部世界的接口（发邮件、改工单、退款）。它写进 Evidence Capsule，是审计时「这个 AI 当时能不能闯祸」的直接证据。Agent 场景里这个声明升级为 approval 节点的人工审批闸。' },
    ],
  },
  bounded_corrective: {
    nodeType: 'bounded_corrective',
    title: '有限纠错检索',
    lane: 'query',
    purpose: '设计目标：证据评分不通过时，改写查询（同义扩展、术语替换）重试检索——但重试次数有编译期强制上限（max_retries），绝不允许无界循环。',
    impact: {
      quality: '对「首次检索措辞不匹配」的问题给第二次机会，提升困难问题的召回。',
      latency: '最坏情况时延 ×(1+max_retries)——上限必须在产品层面被批准而不是代码里随手写。',
      cost: '同上，重试就是重新花钱。',
      risk: '无界自纠错循环是 RAG 生产事故常客（越试越偏、费用失控）。本仓库编译器直接拒绝未声明的环——环必须以 bounded_corrective 显式存在。',
    },
    knobs: [{ name: 'max_retries', effect: '重试上限（设计 0-3）。当前不生效（占位），但编译约束是真实的。', effective: false }],
    assembly: 'v0_6_corrective Recipe 里的 retry 节点。可以现场验证编译约束：试着在画布上连一个普通环，保存会被编译器拒绝。',
    dynamics: {
      why: '一次检索失败不等于库里没有——换个问法常常就找到了；但机器自己换问法必须有闸。',
      ifMissing: '困难问题一次失败就放弃，或者（更糟）工程师用 while 循环私搭纠错。',
      ifOverdone: 'max_retries=5 且每次都全链路重跑：尾部时延不可接受。1 次重试通常拿走大部分收益。',
    },
    liveStatus: 'stub 占位直通：改写与二次检索未实现。但「环必须显式有界」的编译约束是 live 的——结构性安全先于功能实现，这个顺序是有意的。',
    interviewQs: [{ q: '为什么在编译期而不是运行时限制循环？', a: '运行时限制靠自觉（每个开发者记得写计数器），编译期限制靠结构（画布上根本连不出无界环）。把安全约束从「约定」升级为「不可能违反」，是平台型产品的设计责任。' }],
  },

  // ============ 横切件 ============
  cache: {
    nodeType: 'cache',
    title: '缓存',
    lane: 'crosscut',
    purpose: '设计目标：以 question+recipe_hash 为键缓存整次运行结果——重复问题（企业场景占比可观）直接命中，省整条链路的钱和时间。',
    impact: {
      quality: '中性，但有陈旧性风险：文档更新后旧答案还在缓存里。',
      latency: '命中时从秒级降到毫秒级——所有优化里性价比最高的一种。',
      cost: '命中率 × 全链路成本 = 直接节省。',
      risk: '缓存键设计错误是经典事故：不含 recipe_hash 时，改了 Recipe 还命中旧答案，调试时怀疑人生。',
    },
    knobs: [{ name: 'ttl_seconds / key', effect: '过期时间与键构成。当前不生效（占位，HTTP 层也无缓存）。', effective: false }],
    assembly: 'v0_9_operations Recipe 展示其位置（链路最前端）。',
    dynamics: {
      why: '真实流量的问题分布高度头部集中，前 100 个问题可能占 40% 流量。',
      ifMissing: '同一个问题每天烧一百遍同样的嵌入+检索+生成费用。',
      ifOverdone: '语义缓存（相似问题也命中）看似聪明，实则引入「相似但不该同答案」的错误命中——先做精确缓存拿走大头收益。',
    },
    liveStatus: 'stub 占位直通：未实现。注意键设计已写进目录默认值（question+recipe_hash）——设计先行，实现待补。',
    interviewQs: [{ q: '缓存失效怎么和文档更新联动？', a: '完整键应是 question + recipe_hash + 语料版本指纹。本仓库文档带版本号与 SHA-256，指纹的原料已有。没有语料版本联动的缓存，等于给用户一个「随机旧答案」抽奖机。' }],
  },
  rate_limit: {
    nodeType: 'rate_limit',
    title: '限流',
    lane: 'crosscut',
    purpose: '保护下游（模型端点、向量库）不被流量峰值打爆，同时控制成本上限——每个请求都是真金白银。',
    impact: {
      quality: '间接：被打爆的模型端点会超时降级，限流保住的是「稳定的质量」。',
      latency: '被限的请求快速失败或排队——快速失败好过雪崩。',
      cost: '成本的硬顶：没有限流的 LLM 应用等于开了一张不设额度的信用卡。',
      risk: '限流阈值过低误伤正常用户；按谁限（IP/用户/租户）是产品决策。',
    },
    knobs: [{ name: 'requests_per_minute', effect: '节点级配置不生效（占位）；真实限流配环境变量 OPENRAG_RATE_LIMIT_PER_MINUTE，在 API 中间件执行。', effective: false }],
    assembly: 'v0_9_operations 里可见节点形态；真实生效的是服务级中间件——节点说明里明确写了「别把节点摆上画布当成已限流」。',
    dynamics: {
      why: 'LLM 应用的每请求成本是传统 Web 的百倍量级，流量事故直接等于财务事故。',
      ifMissing: '一个失控脚本一夜烧掉一个月预算——真实世界反复发生。',
      ifOverdone: '多层限流互相打架（网关限完中间件限、节点再限），排查「为什么 429」变成考古。一处生效、处处可见才对。',
    },
    liveStatus: '节点是 stub；服务级中间件限流是 live（V0.4 生产横切的遗产）。同一能力在两个层次的不同状态，恰好是「横切面 vs 算法面」两条轴的直观例子。',
    interviewQs: [{ q: '限流放节点级还是服务级？', a: '服务级是底线（保护整个服务），必须先有；节点级是精细化（给某条昂贵 Recipe 单独限额），是后续需求。本仓库先做了服务级、节点留占位——顺序正确，标注诚实。' }],
  },
  graph_query: {
    nodeType: 'graph_query',
    title: '图谱查询',
    lane: 'crosscut',
    purpose: '设计目标：从知识图谱按实体关系召回证据，补向量检索答不了的「关系与全局」问题（多跳、聚合、跨文档关联）。',
    impact: {
      quality: '对关系类问题是从 0 到 1；对普通事实问题无增益。',
      latency: '图遍历毫秒级，但前置的实体识别可能要一次模型调用。',
      cost: '大头在索引期：LLM 抽取实体关系的 token 成本是普通嵌入的数十倍，且增量更新困难。',
      risk: '抽取错误进图后比坏 chunk 更隐蔽——错的「边」会被多个查询复用。',
    },
    knobs: [{ name: '（当前配置不生效）', effect: '需要 graph profile + Neo4j（未内置）。', effective: false }],
    assembly: 'v0_7_graph Recipe 展示其位置（与稠密并行、汇入 context）。执行时共享稠密结果（fallback），Trace 如实标注。',
    dynamics: {
      why: '向量检索假设「答案在某个片段里」，而「A 和 B 什么关系」的答案在片段之间。',
      ifMissing: '关系类问题只能靠碰运气（恰好有片段同时提到 A 和 B）。',
      ifOverdone: '给以 FAQ 为主的知识库上 GraphRAG：付了数十倍索引税，问题分布里关系类不到 5%——先统计问题类型再决策（见方案对比 GraphRAG 章）。',
    },
    liveStatus: 'fallback 退化：未接图数据库，共享稠密/词法结果。保留节点是为了讲清这条路线在整体架构里的位置。',
    interviewQs: [{ q: '怎么判断该不该上图路线？', a: '拉一个月的真实问题日志做类型标注：片段可答 vs 需要跨文档关系。后者占比、单价（答对的业务价值）、语料更新频率三个数决定 ROI。多数知识库场景的诚实答案是「暂不需要」。' }],
  },
  pdf_page_retrieve: {
    nodeType: 'pdf_page_retrieve',
    title: 'PDF 页级检索（多模态）',
    lane: 'crosscut',
    purpose: '设计目标：把 PDF 页面当图检索（ColPali 类视觉嵌入），图表、版面、扫描件不经 OCR 直接可检索。',
    impact: {
      quality: '对图表密集型文档（财报、工程图册）是从 0 到 1；纯文本文档无增益。',
      latency: '视觉嵌入与多向量检索都比文本路重。',
      cost: '页级视觉嵌入的索引与存储成本显著高于文本嵌入。',
      risk: '生成端也要多模态模型配合，链路整体复杂度上升。',
    },
    knobs: [{ name: '（当前配置不生效）', effect: '需要 multimodal profile（未内置）。', effective: false }],
    assembly: 'v0_8_multimodal Recipe 展示位置；执行时退化共享稠密结果，Trace 标注。',
    dynamics: {
      why: '有些知识只存在于图表与版面里，文本管道天然看不见。',
      ifMissing: '图表内容对系统不存在——「Q3 增长率图里是多少」永远答不了。',
      ifOverdone: '全库上视觉检索而其实 90% 是纯文本：按文档类型路由（parse_route 的思想延伸）才是正解。',
    },
    liveStatus: 'fallback 退化：未实现视觉检索。',
    interviewQs: [{ q: '视觉检索和 OCR+文本检索怎么选？', a: 'OCR 路线便宜、复用文本管道，但版面与图形语义丢失；视觉路线保真、贵。判据是错误容忍度：财务数字读错的代价高就值得视觉路线，一般文档 OCR 够用。' }],
  },
  approval: {
    nodeType: 'approval',
    title: '人工审批闸',
    lane: 'crosscut',
    purpose: '受控 Agent 的关键闸门：链路在此停住，产出物标记 approval_required，等人签字——框架绝不代替人做有副作用的决定。',
    impact: {
      quality: '人是最后的质检员——对低频高危操作，人审的精度机器暂时替代不了。',
      latency: '从秒级变成「人回来为止」——这是特性不是缺陷。',
      cost: '人力成本，应该只花在高危路径上。',
      risk: '审批疲劳：什么都要批的系统，批准会变成条件反射——闸门要少而关键。',
    },
    knobs: [{ name: 'required', effect: '固定为 true 是有意设计：这个节点存在的意义就是「必须有人」。', effective: true }],
    assembly: 'v1_controlled_agent Recipe 末端：question → dense → build_ticket_draft → approval。运行后结果页可见待审批的工单草稿。',
    dynamics: {
      why: 'Agent 的能力边界应该由结构决定而不是由 Prompt 决定——「请不要直接提交」是恳求，approval 节点是物理闸门。',
      ifMissing: 'Agent 直接执行副作用操作，一次幻觉就是一次真实业务事故。',
      ifOverdone: '全流程处处审批 = 自动化收益归零 + 审批疲劳。正确姿势：只闸「不可逆副作用」。',
    },
    liveStatus: 'live：真实执行，运行在此停住，绝不自动放行。',
    interviewQs: [{ q: 'Human-in-the-loop 怎么设计才不是摆设？', a: '三要素：给审批人完整上下文（草稿+证据+缺失字段清单，本仓库的胶囊正是这个）；审批动作可审计（谁何时批了什么）；拒绝路径有出口（打回修改而不是死掉）。没有上下文的审批只是往锅里加一个背锅的人。' }],
  },
  build_ticket_draft: {
    nodeType: 'build_ticket_draft',
    title: '工单草稿构建（受控 Agent 示例）',
    lane: 'crosscut',
    purpose: '从用户消息抽取工单字段（启发式正则），缺什么列什么，产出结构化草稿 + 禁用动作清单——展示「RAG 之上的受控 Agent」长什么样。',
    impact: {
      quality: '结构化草稿比自由文本转人工的效率高得多；缺失字段清单让人工补齐有的放矢。',
      latency: '正则抽取微秒级。',
      cost: '近零（不调模型）。',
      risk: '正则抽取只是演示级，字段错漏率高——所以必须搭配 approval 闸。',
    },
    knobs: [{ name: '字段规则', effect: '在 app.py 中按业务工单模型扩展（代码级）。', effective: true }],
    assembly: 'v1_controlled_agent 里的 draft 节点。运行后看结果页的「Agent 工单草稿（待人工审批）」。',
    dynamics: {
      why: '问答之后的下一步价值是「帮用户把事办了」——但办事必须受控，草稿+审批是最保守可靠的形态。',
      ifMissing: '要么停留在纯问答，要么跳到无闸 Agent——中间形态缺失。',
      ifOverdone: '在演示框架里实现完整工单系统——越界了，它的职责是把「受控」的形态讲清楚。',
    },
    liveStatus: 'live：真实执行，但抽取是启发式正则（生产应换受约束的结构化抽取，如 function calling + schema 校验），节点说明里写明。',
    interviewQs: [{ q: '为什么用正则不用 LLM 抽字段？', a: '演示框架的取舍：正则零依赖、行为确定、演示可复现。生产的正解是 schema 约束的模型抽取 + 字段级校验。重要的是形态（草稿→缺失清单→审批）而不是抽取技术本身。' }],
  },

  // ============ 系统级环节 ============
  _evidence_capsule: {
    nodeType: '_evidence_capsule',
    title: 'Evidence Capsule（证据胶囊）',
    lane: 'system',
    purpose: '每次运行导出一个自包含 JSON：问题、Recipe 哈希、模型配置、全部证据引用、安全决策、完整 Trace。审计不用信截图，直接读胶囊。',
    impact: {
      quality: '不改变单次答案质量，改变的是质量的「可追责性」——坏答案可以完整复盘。',
      latency: '导出是异步下载，不在查询路径上。',
      cost: '存储成本（每次运行一份 JSON）。',
      risk: '胶囊里含问题原文与证据内容——保留期与脱敏策略是接真实数据前必须补的合规项。',
    },
    knobs: [{ name: '（无运行时旋钮）', effect: '内容结构由框架定义。', effective: true }],
    assembly: '不是画布节点，是运行的输出物。任何一次真实运行后，结果页点「下载 Evidence Capsule」。',
    dynamics: {
      why: '企业采信一个 AI 系统的前提是可审计。「当时为什么这么答」必须五分钟内给出完整证据链，而不是拉工程师查日志考古。',
      ifMissing: '合规、法务、客诉场景全部过不了——「我们的 AI 当时看到什么」答不出来。',
      ifOverdone: '把全量中间张量都塞进胶囊：体积爆炸。胶囊要的是「决策证据」不是「内存快照」。',
    },
    liveStatus: 'live：真实导出，包含上述全部字段。复现三要素（Recipe 哈希 + 文档版本 + 模型 ID）都在其中。',
    interviewQs: [{ q: '胶囊和日志有什么本质区别？', a: '日志是工程师视角的碎片流水，胶囊是业务视角的自包含决策档案——一个 run_id 一份、拿走就能离线审。设计隐喻来自飞行数据记录仪：事故复盘不应该依赖「当时的服务器还在不在」。' }],
  },
  _eval: {
    nodeType: '_eval',
    title: 'Eval（评测体系）',
    lane: 'system',
    purpose: '给整条流水线一把尺子：检索质量（Hit@k / MRR）、引用忠实度、安全拦截率。没有评测，所有调参都是玄学，所有「优化」都无法验收。',
    impact: {
      quality: '不直接产生质量，但决定质量能不能被管理——「上了重排提升多少」没有评测就永远答不出。',
      latency: '离线运行，不在查询路径。',
      cost: '标注黄金集的人力是主要成本；这笔钱是所有后续优化决策的地基。',
      risk: '评测集偏离真实流量分布时，指标会给出虚假的安全感——要定期用线上真实问题补充。',
    },
    knobs: [{ name: '黄金集（问题→应命中 chunk→应引用来源）', effect: '规模建议从 20-50 条起步，覆盖主要问题类型。', effective: true }],
    assembly: '不是画布节点：见 docs/golden-eval-v0.1-dev.md 与 eval/golden.py（CLI 运行）。工作台内暂无评测页——这是明确的产品欠账，理想形态是「改完配置一键跑评测对比」。',
    dynamics: {
      why: 'RAG 的参数空间巨大（切分×top_k×阈值×模型×…），没有尺子的调参是布朗运动。',
      ifMissing: '本仓库自己就是例子：稀疏/重排迟迟不做的理由正是「没有基线测不出收益」——评测是解锁一切后续投入的钥匙。',
      ifOverdone: '追求几十个学术指标：团队看不懂也不行动。三个够了：Hit@5（检索）、引用忠实率（生成）、该拒答时拒答率（安全）。',
    },
    liveStatus: 'live（CLI 级）：golden eval 脚本真实存在并可运行（docs/golden-eval-v0.1-dev.md 有结果）；未集成进工作台 UI。',
    interviewQs: [
      { q: 'Hit@k 和 MRR 分别说明什么？', a: 'Hit@k：正确证据出现在前 k 条的比例——检索有没有捞到；MRR：正确证据平均排第几（倒数均值）——捞到之后排得好不好。Hit@5 高但 MRR 低 = 该上重排的信号；Hit@5 就低 = 先修召回（切分/嵌入/混合），上重排没用。两个指标合起来就是检索优化的诊断表。' },
      { q: '引用忠实度怎么测？', a: '对答案里每个 [S#] 引用句，核对引用的 chunk 是否真支持该句（人工抽检或用模型辅助判断再抽检模型）。它是 RAG 最该对外承诺的指标——「我们的答案 98% 可溯源」比「我们的答案很准」可验证得多。' },
    ],
  },
}

/** 环节地图的展示顺序（按泳道） */
export const STAGE_MAP_ORDER: { lane: string; title: string; types: string[] }[] = [
  {
    lane: 'ingest',
    title: '摄取线：文档怎么进来',
    types: ['parse_route', 'native_parser', 'pdf_parser', 'office_parser', 'tabular_parser', '_block_model', 'chunker', 'metadata_enricher', 'embed_index'],
  },
  {
    lane: 'query',
    title: '查询线：问题怎么被回答',
    types: ['question', 'intent_router', 'metadata_filter', 'dense_retrieve', 'sparse_retrieve', 'rrf_fusion', 'reranker', 'parent_expansion', 'context_builder', 'llm_generate', 'evidence_grade', 'bounded_corrective', 'policy_gate'],
  },
  {
    lane: 'crosscut',
    title: '横切件与受控 Agent',
    types: ['cache', 'rate_limit', 'graph_query', 'pdf_page_retrieve', 'build_ticket_draft', 'approval'],
  },
  {
    lane: 'system',
    title: '系统级环节（不在画布上，但在体系里）',
    types: ['_evidence_capsule', '_eval'],
  },
]
